### ISSUE TITLE
Design fix: Add responsiveness to the website

### ISSUE THREAD

**Issue by yashsehgal** [yashsehgal/personal-website#2]
The current website is not responsive for tablet and mobile devices. Need to work on the responsiveness using TailwindCSS class system.

**Comment by NizarAhamed97** [comment]
I would like to work on the issue

**Comment by yashsehgal** [comment]
> I would like to work on the issue

Ref: https://github.com/yashsehgal/personal-website/issues/3#issuecomment-1278434884
