### ISSUE TITLE
Design Feature: Adding hover sliding feature to Navbar options

### ISSUE THREAD

**Issue by yashsehgal** [yashsehgal/personal-website#3]
For reference, this is the kind of feature I want to have in the website
https://codepen.io/Web_Cifar/pen/bGdVOaW

**Comment by NizarAhamed97** [comment]
Would like to work on this.

**Comment by yashsehgal** [comment]
> Would like to work on this.

Hey @NizarAhamed97 
Thanks for showing interest in working on this issue, actually this issue has been assigned to one of my team members, so I need to assign it to him. But I really appreciate your time & interest.

Meanwhile, you can look for issues or maybe raise one in this repository: https://github.com/hekors/hacktoberfest-with-hekors

Would love to have you contributing to that project, Happy Hacking! 🚀 💕

**Comment by Nishantjain10** [comment]
Hey, Please allow me to work on this issue.
